In [33]:
import tensorflow as tf
print(("Your TensorFlow Version: {0}").format(tf.__version__))

Your TensorFlow Version: 2.21.0


In [34]:
# Create a constant tensor A
A = tf.constant([[4,3],
                [6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [35]:
# Create a variable tensor V
V = tf.Variable([[3,1],
                [5,2]])
# Create another tensor B
B = tf.constant([[7,8],
                 [4,5]])
print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]], dtype=int32)>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]], dtype=int32)>

In [36]:
# Concatenate columns ~ (2,2,2)
AB_concatenated = tf.concat(values=[A,B], axis =1)
AB_concatenated


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]], dtype=int32)>

In [37]:
AB_concatenated = tf.concat(values=[A,B], axis =0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]], dtype=int32)>

In [38]:
print("Hello")

Hello


In [39]:
import tensorflow as tf

tensor = tf.random.uniform([3,4])
print(tensor)

tf.Tensor(
[[0.6051574  0.60946655 0.8139688  0.17484713]
 [0.54928005 0.06874263 0.6259079  0.4446373 ]
 [0.24377155 0.6741265  0.34464395 0.1610403 ]], shape=(3, 4), dtype=float32)


In [40]:
import tensorflow as tf

# Step 1: Create random tensor
tensor = tf.random.uniform([3, 4])
print("Original Tensor:\n", tensor)

# Step 2: Reshape tensor
reshaped_tensor = tf.reshape(tensor, [4, 3])
print("\nReshaped Tensor:\n", reshaped_tensor)

Original Tensor:
 tf.Tensor(
[[0.14941287 0.10185516 0.05146289 0.81783485]
 [0.29482388 0.4811405  0.55856824 0.47667718]
 [0.8297949  0.01017201 0.8412082  0.16184759]], shape=(3, 4), dtype=float32)

Reshaped Tensor:
 tf.Tensor(
[[0.14941287 0.10185516 0.05146289]
 [0.81783485 0.29482388 0.4811405 ]
 [0.55856824 0.47667718 0.8297949 ]
 [0.01017201 0.8412082  0.16184759]], shape=(4, 3), dtype=float32)


In [43]:
import tensorflow as tf

# Original tensor
tensor = tf.constant([[4.6, 4.2],
                      [7.5, 3.6],
                      [2.7, 9.4],
                      [6.7, 8.3]], dtype=tf.float32)

# Convert to int
tensor_as_int = tf.cast(tensor, tf.int32)

# Print both
print("Original Tensor:\n", tensor)
print("\nConverted to int:\n", tensor_as_int)

Original Tensor:
 tf.Tensor(
[[4.6 4.2]
 [7.5 3.6]
 [2.7 9.4]
 [6.7 8.3]], shape=(4, 2), dtype=float32)

Converted to int:
 tf.Tensor(
[[4 4]
 [7 3]
 [2 9]
 [6 8]], shape=(4, 2), dtype=int32)


In [45]:
a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 6],
       [4, 3, 9, 8]], dtype=int32)>

In [47]:
import tensorflow as tf

# Matrix A (2x2)
A = tf.constant([[5, 8],
                 [3, 9]])

# Vector v (2x1)
v = tf.constant([[4],
                 [2]])

# Matrix multiplication
Av = tf.matmul(A, v)

print("Result:\n", Av)

Result:
 tf.Tensor(
[[36]
 [30]], shape=(2, 1), dtype=int32)


In [48]:
# Element-wise multiplication
Av = tf.multiply(A,v)
Av

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]], dtype=int32)>

In [52]:
import tensorflow as tf

# Correct matrix (3x2)
A = tf.constant([[4, 9],
                 [5, 6],
                 [1, 8]])

# Get shape
rows, columns = A.shape
print("rows:", rows, "columns:", columns)

# Identity matrix
A_identity = tf.eye(num_rows=rows,
                    num_columns=columns,
                    dtype=tf.int32)

print("\nMatrix A:\n", A)
print("\nIdentity Matrix:\n", A_identity)

rows: 3 columns: 2

Matrix A:
 tf.Tensor(
[[4 9]
 [5 6]
 [1 8]], shape=(3, 2), dtype=int32)

Identity Matrix:
 tf.Tensor(
[[1 0]
 [0 1]
 [0 0]], shape=(3, 2), dtype=int32)
